server:
  port: 0

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3308/msa_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        hbm2ddl.extra_physical_table_types: PARTITIONED TABLE
  logging:
    level:
      org.hibernate.SQL: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${random.value}}
    prefer-ip-address: true