server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: first-service
              uri: # 요청을 처리할 서비스 주소
                  http://localhost:8081
              predicates: # predicates 로 오는것은 uri 로 넘긴다
                - Path=/first-service/**
            - id: second-service
              uri:
                  http://localhost:8082
              predicates:
                - Path=/second-service/**
